<?php
/**
 * Created by PhpStorm.
 * User: keysnt
 * Date: 03/04/2018
 * Time: 11:37
 */
namespace Magenest\AdvancedProductOption\Block\Adminhtml\Stores\Config;

class Date extends \Magento\Config\Block\System\Config\Form\Field{
    public function render(\Magento\Framework\Data\Form\Element\AbstractElement $element){
        $element->setDateFormat(\Magento\Framework\Stdlib\DateTime::DATE_INTERNAL_FORMAT);
        $element->setTimeFormat(null);
        return parent::render($element); // TODO: Change the autogenerated stub
    }
}